### ISSUE TITLE
Valid Aggregations

### ISSUE THREAD

**Issue by philippfriberg** [qualiture/ui5-validator#7]
Hi Robin

I should test InputFields in sap.m.table. For that I need the Aggregation "cells".

In Line 54:
`aPossibleAggregations = ["cells", "items", "content", "form", "formContainers", "formElements", "fields", "sections", "subSections", "_grid"],`

Do you see any problems?

Regards Philipp

**Comment by qualiture** [comment]
Hi @philippfriberg,

I don't see any issues with that -- feel free to submit your changes 👍
